### ISSUE TITLE
Docs: struttura del sito

### ISSUE THREAD

**Issue by Flecart** [csunibo/note-website#2]
Cerchiamo di creare un workflow utile: dalla struttura generale del sito (pagine) alle singole funzioni che deve avere.

Potete proporre soluzioni qua.
1.  Le pagine **principali del sito**, cosa vogliamo mostrare?
2.  Per chi sarà il nostro sito? Solo per la nostra classe? Se sì bisognerebbe sapere quale genere di cose ci serve: solo appunti? Anche spiegazioni semplificate da studente a studente? Flashcard? Mappe concettuali? 
3. Cerchiamo a rispondere a **Quali sono i contenuti principali del sito**?

**Comment by MaxPignatti** [comment]
2) Secondo me sarebbe meglio inizialmente dedicarci alla facoltà di Informatica per appunti e resto. Potrebbe essere carina una parte dedicata agli appunti (già presente) e una parte forum dove le persone possano fare domande. Nella parte degli appunti si potrebbero anche mettere dei commenti (magari qualche studente vuole fare una precisazione su un concetto, c'è qualche errore all'interno o semplicemente non si è capito bene un concetto). I commenti potrebbero essere visualizzati da quello con più "mi piace" a quello con meno. 
Inoltre si potrebbe dare anche la possibilità agli stessi studenti di pubblicare appunti, schemi e mappe, ma questo sarebbe più complicato da gestire.
