### ISSUE TITLE
Docs: Struttura del codice

### ISSUE THREAD

**Issue by Flecart** [csunibo/note-website#3]
Direi che possiamo discutere di questo dopo oggi:

1.  Struttura dei database, dobbiamo decidere quali informazioni salvare.
2.  Framework back-end e front-end da utilizzare: per me dovremmo deciderle secondo:
a. Skill attuali del gruppo di lavoro (e.g. se in 3 conoscono bene react e uno Vue è più conveniente React)
b. Qualità delle documentazioni e supporto a lungo termine della piattaforma
c. Eventuali costi? (preferibilmente 0 xD dai)
d. Se qualcuno ha altri parametri da valutare consigli pure, per me il punto a. è la principale da valutare se vogliamo iniziare a fare subito qualcosa, se no possiamo piano piano imparare un nuovo framework per chi non conosce.
3. Creare struttura del codice? Le funzioni principali e la logica di base da riempire dopo.

**Comment by paologaleotti** [comment]
per il backend suggerisco firebase o Supabase, il secondo usa un database relazionale SQL che penso conosciamo tutti. in questo modo è più semplice da capire per tutti

per il frontend sono neutrale, posso dare una mano sullo stile e sul design e magari suggerisco di usare Bootstrap o Semantic UI come framework CSS

**Comment by Flecart** [comment]
per scrivere codice assieme ci dovrebbe essere un estensione di VScode, è molto comoda.
Peter ha consigliato mondoDB come database backend.
